(package "flycheck-eask"
         "0.1.0"
         "Eask support in Flycheck")

(website-url "https://github.com/emacs-eask/flycheck-eask")
(keywords "lisp" "eask")

(package-file "flycheck-eask.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "flycheck")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
